import asyncio
import logging
import os

import discord
from discord import app_commands
from discord.ext import commands

from .db_handler import (
    get_verification_code_by_server_link_code,
    initialize_discord_db_pool,
    lookup_app_id_and_assign_user,
)

# --- CONFIGURATION ---

DISCORD_APPLICATION_ID = os.getenv("DISCORD_APP_ID")

logger = logging.getLogger(__name__)


# --- BOT SETUP ---

# Initialize the bot
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix="$", intents=intents, application_id=DISCORD_APPLICATION_ID)

# Global variable to store the running bot instance
global_bot_instance = None


# A simple on_ready event to confirm the bot is running
@bot.event
async def on_ready():
    logger.debug(f"Discord bot logged in as {bot.user.name} ({bot.user.id})")
    await asyncio.sleep(0.1)
    if not bot.application_id:
        logger.error("❌ Fatal: bot.application_id is still missing after sleep. Cannot sync commands.")
        return

    await initialize_discord_db_pool(loop=bot.loop)
    await bot.tree.sync()

    logger.debug("Commands synced successfully.")
    logger.debug("------")

    global global_bot_instance
    global_bot_instance = bot


@bot.command()
async def hello(ctx):
    await ctx.send("Hello! I'm ready to receive messages from the API.")


# --- SLASH COMMANDS ---


@bot.tree.command(name="link", description="Link your Discord account to your application user ID.")
@app_commands.describe(link_id="The unique linking ID provided by the application.")
async def link_account(interaction: discord.Interaction, link_id: str):
    """
    Links the user's Discord account to a unique ID generated by the external application.
    """
    user_id = interaction.user.id

    # Defer the response since the DB call might take time
    await interaction.response.defer(ephemeral=True)

    # 1. Look up the App ID using the provided link_id and attempt to link the user.
    if await lookup_app_id_and_assign_user(link_id, user_id):
        embed = discord.Embed(
            title="✅ Account Linked Successfully",
            description=(
                f"Your Discord account ({interaction.user.mention}) has been successfully linked."
                "\n\nIf you need a verification code, please use `/verify <server_code>`."
            ),
            color=discord.Color.green(),
        )

        # Follow-up message is used after deferring. ephemeral=True ensures privacy.
        await interaction.followup.send(embed=embed, ephemeral=True)
    else:
        # Failed linking
        embed = discord.Embed(
            title="❌ Linking Failed",
            description=(
                f"The linking ID `{link_id}` is invalid or has expired."
                "\nPlease check the ID provided by your application or contact support."
            ),
            color=discord.Color.red(),
        )
        await interaction.followup.send(embed=embed, ephemeral=True)


async def _handle_verification_followup(interaction: discord.Interaction, server_link_code: str):
    """Handles the database lookup and sending the final message."""

    # 1. Attempt to generate/fetch the code using the provided server_link_code
    verification_code, app_id = None, None
    result = await get_verification_code_by_server_link_code(server_link_code)
    print(result)
    if result:
        verification_code = result

        embed = discord.Embed(
            title="🔑 Your Verification Code",
            description=(
                "This code is only visible to you. Use it immediately in the application to complete your action (registration/reset)."
            ),
            color=discord.Color.blue(),
        )
        embed.add_field(name="Code", value=f"```\n{verification_code}\n```", inline=False)

        await interaction.followup.send(embed=embed, ephemeral=True)
    else:
        embed = discord.Embed(
            title="❌ Code Retrieval Failed",
            description=(
                f"The server link code `{server_link_code}` is invalid or has expired."
                "\nPlease ensure you copied the correct code from the application."
            ),
            color=discord.Color.red(),
        )
        await interaction.followup.send(embed=embed, ephemeral=True)


@bot.tree.command(
    name="verify",
    description="Retrieve your private verification code using the server-generated link code.",
)
@app_commands.describe(server_link_code="The temporary code provided by the application (e.g., 34as32).")
async def get_verification_code(interaction: discord.Interaction, server_link_code: str):
    try:
        # Acknowledge the interaction within 3 seconds
        await interaction.response.defer(ephemeral=True)
    except discord.errors.NotFound:
        # This interaction has expired. Stop execution here.
        logging.error(discord.errors)
        return
    except Exception as e:
        logger.error(f"Error during initial deferral: {e}")
        return

    # 2. Launch the rest of the logic in a new, non-blocking task
    await _handle_verification_followup(interaction, server_link_code)


# --- RUN BOT ---


def run_bot():
    """
    A synchronous function to start the bot.
    This is called from a separate thread.
    """
    bot_token = os.getenv("DISCORD_BOT_TOKEN")
    if not bot_token:
        logger.error("❌ Error: 'DISCORD_BOT_TOKEN' environment variable is not set.")
        return
    bot.run(bot_token)


def get_bot() -> commands.Bot:
    """Returns the globally running bot instance."""
    return global_bot_instance
